"""empty message

Revision ID: 1ee2c558199d
Revises: d08e221875cd
Create Date: 2026-03-05 19:43:05.219371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee2c558199d'
down_revision = 'd08e221875cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint('personajes_nombre_key', type_='unique')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_constraint('planetas_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.create_unique_constraint('planetas_nombre_key', ['nombre'])

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.create_unique_constraint('personajes_nombre_key', ['nombre'])

    # ### end Alembic commands ###
