"""empty message

Revision ID: 5c3b95de4e07
Revises: 4fd246c00f0d
Create Date: 2026-03-04 01:09:45.039158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3b95de4e07'
down_revision = '4fd246c00f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('raza', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.Column('color_de_ojos', sa.String(length=120), nullable=False),
    sa.Column('color_de_piel', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('poblacion', sa.String(length=120), nullable=False),
    sa.Column('terreno', sa.String(length=120), nullable=False),
    sa.Column('diamentro', sa.Integer(), nullable=False),
    sa.Column('clima', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('user_sw', schema=None) as batch_op:
        batch_op.drop_constraint('user_sw_fecha_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sw', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_sw_fecha_key', ['fecha'])

    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
