"""empty message

Revision ID: 6988a58037bc
Revises: a9fc212ab220
Create Date: 2026-03-05 15:43:06.974631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6988a58037bc'
down_revision = 'a9fc212ab220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajesfavoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sw_id', sa.Integer(), nullable=False),
    sa.Column('personajes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['user_sw_id'], ['user_sw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajesfavoritos')
    # ### end Alembic commands ###
