"""empty message

Revision ID: 83493370f87a
Revises: 6988a58037bc
Create Date: 2026-03-05 15:52:20.430556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83493370f87a'
down_revision = '6988a58037bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('personajesfavoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajesfavoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_sw_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personajes_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], name='personajesfavoritos_personajes_id_fkey'),
    sa.ForeignKeyConstraint(['user_sw_id'], ['user_sw.id'], name='personajesfavoritos_user_sw_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personajesfavoritos_pkey')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###
