"""empty message

Revision ID: a9fc212ab220
Revises: 5c3b95de4e07
Create Date: 2026-03-04 01:29:38.621544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fc212ab220'
down_revision = '5c3b95de4e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diametro', sa.Integer(), nullable=True))
        batch_op.drop_column('diamentro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diamentro', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('diametro')

    # ### end Alembic commands ###
