"""empty message

Revision ID: c31c0c790c0f
Revises: c135bf944c38
Create Date: 2026-03-07 01:40:24.279565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31c0c790c0f'
down_revision = 'c135bf944c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('raza',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('color_de_ojos',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('color_de_piel',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('poblacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('terreno',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('poblacion',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.alter_column('color_de_piel',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('color_de_ojos',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('genero',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('raza',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
